// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swtvkprypwusbejiozmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dHZrcHJ5cHd1c2Jlamlvem16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODExMDksImV4cCI6MjA3MjU1NzEwOX0.SaKRlN4lABNpEiqEH1b4NhKMg23iL-PlXlSJK37dZAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});